### ISSUE TITLE
Installation instructions error

### ISSUE THREAD

**Issue by Pumych** [tsanko/angular-multiline-ellipsis#2]
`<script src="../bower_components/angular-multiline-ellipsis/dist/multi-line-ellipsis.min.js"></script><link rel="stylesheet" href="/../bower_components/angular-multiline-ellipsis/dist/multi-line-ellipsis.min.css" />`

should be instead of 

`<script src="../bower_components/angular-multiline-ellipsis/dist/angular-multiline-ellipsis.min.js"></script><link rel="stylesheet" href="/../bower_components/angular-multiline-ellipsis/dist/angular-multiline-ellipsis.min.css" />`

**Comment by tsanko** [comment]
Fixed - thanks.
